# Generated by Django 3.2.4 on 2022-03-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fan',
            new_name='Flan',
        ),
    ]
