# Generated by Django 3.2.4 on 2022-03-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_flan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='deseo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
