# Generated by Django 3.2.4 on 2022-03-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_flan_deseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='deseo',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
