# Generated by Django 3.2.4 on 2022-03-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_flan_deseo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='deseo',
        ),
    ]
